### PR TITLE
MERGE-BY-REBASE: feat(cli): `tc-cli build` command

### PR DESCRIPTION
**Pull request by pklaschka**
Closes: #263

### CODE REVIEW

**Comment by pklaschka** [comment]
image

**Comment by pklaschka** [comment]
Adding the extensibility, because of its complexity, will be considered "out of scope" for this PR or release 🙂

**Review by fussel178 — APPROVED** [review]
LGTM. Thank you for your contribution :hamburger:

**Review by fussel178 — APPROVED** [review]
LGTM. :bell:

**Pull request merged**
